### ISSUE TITLE
Can I ask question about importing Insurgency: Sandstorm animations?

### ISSUE THREAD

**Issue by BreenBB** [KernCore91/-SC-Insurgency-Weapons-Project#4]
Hello and sorry to bother you this way, I want to port animation from Ins: Sandstorm by myself using Gildor Umodel, some animations are imported correctly, Idle, Reload ones, but some like Draw, Holster, Shoot and switching to GL mode are imported this way: https://imgur.com/a/14VZ4qn

Interesting, how you ported these animations correctly? I asked Gildor himself, author of Umodel tool, he said that these are additive animations and right now they are unsupported, and he said what he for few months will be busy and unable to work on Umodel, since your pack have these animations, I decided ask how you dealt with them. 

I have idea, load in 3d editor idle animation, and when load somehow on top of that animation one of these additive animations, but I don't know how to perform that in 3DS Max or Blender.

**Comment by DNIO071** [comment]
Hi, my explanation might not be the best, and other people who port stuff from Sandstorm might have better ways to do things (like those who ported stuff to Insurgency's steam Workshop), but I'll answer to the best of my knowledge.

To port the animations I basically rebuilt the bone structure needed for the weapon (main weapon bone, magazine bone, bolt, trigger, etc) so I end up with the kind of setup that would allow me to animate it myself, if I needed to, with IK (Inverse Kinematics) applied to the hands at proper times so they stick to the weapon movement.

Because of said setup I'm able to import the file and remap the movement from the main weapon bone (b_wpn) to the ones I made.

![mk18_inss_01](https://user-images.githubusercontent.com/11966319/115261934-71726780-a10a-11eb-9c2b-a3e7d27718d8.png)

It was only on the MK18 I used Draw and Holster animations from Sandstorm, as it's the most recent port I made, the AKM and the SKS use the ones from Insurgency (2014). For the specific case of the AKM's GL switching, I moved the finger bones myself, and relied on a similar setup to map the animation movement.

![akm_inss_01](https://user-images.githubusercontent.com/11966319/115263664-fca02d00-a10b-11eb-9b82-2ccb598b5a64.png)

The idea of loading the additive animation on top is good, but the way I've tried to get it to work in Max it still ended with the animation all messed up, and I don't work with Blender so I couldn't help there. Might need to take a further look into animation layers.

Hope this information helped somewhat, I worked with what I could in terms of porting stuff that fit the project

**Comment by BreenBB** [comment]
Thanks for reply! 

I was thinking about something like you showed, maybe a bit differently - move weapon bone in one of these additive animation on position of idle animation, weapon movement itself seems fine except what it moved to center of the scene, when import hands pose from idle animation, and then use IK Limb Solver on both hands and after that attach these solvers to weapon bone so hands will move with weapon.
